-- AlterTable
ALTER TABLE "AttendanceRecord" ALTER COLUMN "scannerLat" SET DATA TYPE DECIMAL(13,10),
ALTER COLUMN "scannerLng" SET DATA TYPE DECIMAL(13,10);

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "locationLat" SET DATA TYPE DECIMAL(13,10),
ALTER COLUMN "locationLng" SET DATA TYPE DECIMAL(13,10);
